### PR TITLE
adding an option to mark build as failed instead of just unstable when ...

### PR DESCRIPTION
**Pull request by moshjeier**
a test or configuration fails.

### CODE REVIEW

**Comment by damienbiggs** [comment]
I added a pull request that's similar to this one
https://github.com/jenkinsci/testng-plugin-plugin/pull/19

it seems like the plugin isn't under active development?
The last commit was in October.

**Comment by nullin** [comment]
Yup, not under active dev, just maintenance mode. I'll look in these pull requests as soon as I can get to them. Thanks!

**Comment by damienbiggs** [comment]
Thanks nulllin.
I'd be willing to help review pull requests if that would help.

**Comment by nullin** [comment]
Merged in pull #19. Also see [JENKINS-20985](https://issues.jenkins-ci.org/browse/JENKINS-20985), which seems like another way to go.

**Pull request closed without merging**
