### PR TITLE
Fix JENKINS-32746: Change loop determination condition in order to check all loaded builds

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by juherr** [comment]
Ping @jenkinsci/code-reviewers

**Comment by juherr** [comment]
Ping @jenkinsci/code-reviewers

**Comment by batmat** [comment]
Test @jenkinsci/code-reviewers

**Comment by batmat** [comment]
Weird, the first ping @juherr was inactive, and became bold and clickable when I edited it. But still not visible in https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+team%3Ajenkinsci%2Fcode-reviewers
I became listed in the link above when I added the last comment... 

Wasn't aware that there was possibly something like access rights for pinging some GitHub team? That would somehow defeat the purpose of this one BTW.

**Comment by batmat** [comment]
So, apparently it's normal IIUC: 
image

As @juherr is not (yet :-)) part of the jenkinsci GH org.

**Comment by juherr** [comment]
@batmat @batmat Someone could merge? :)

**Comment by oleg-nenashev** [comment]
@nullin Hi, it would be great to get a feedback from you

**Comment by nullin** [comment]
lgtm!

**Pull request merged**
